require('dotenv').config({ path: '../../.env' });
const mongoose = require('mongoose');
const AIModel = require('../models/AIModel');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/nexusai-db';

const models = [
  { slug:'gpt-4o', name:'GPT-4o', provider:'OpenAI', providerColor:'#10a37f', categories:['Text Generation','Multimodal','Code','Reasoning','Chat'], description:"OpenAI's flagship multimodal model with native vision, audio, and text. Delivers GPT-4 intelligence at faster speeds with improved instruction following.", contextWindow:128000, pricing:{input:2.5,output:10.0,unit:'per 1M tokens',tier:'mid'}, strengths:['Exceptional multimodal understanding','Fast response times','Strong instruction following','Real-time audio processing','Superior long-context handling'], limitations:['Knowledge cutoff may lag','Occasional hallucinations on niche topics','API costs at scale'], scores:{reasoning:95,coding:90,creativity:88,speed:85,multimodal:97,contextHandling:90,costEfficiency:72}, releaseDate:'2024-05', openSource:false, apiAvailable:true },
  { slug:'gpt-4-turbo', name:'GPT-4 Turbo', provider:'OpenAI', providerColor:'#10a37f', categories:['Text Generation','Reasoning','Code','Chat'], description:'High-capability GPT-4 variant with 128K context, vision support, and deep reasoning for complex tasks.', contextWindow:128000, pricing:{input:10.0,output:30.0,unit:'per 1M tokens',tier:'premium'}, strengths:['Deep reasoning chains','Vision capabilities','128K context window','Complex instruction following'], limitations:['Higher pricing vs newer models','Slower than GPT-4o','Older generation'], scores:{reasoning:93,coding:88,creativity:85,speed:68,multimodal:80,contextHandling:90,costEfficiency:50}, releaseDate:'2024-01', openSource:false, apiAvailable:true },
  { slug:'gpt-3-5-turbo', name:'GPT-3.5 Turbo', provider:'OpenAI', providerColor:'#10a37f', categories:['Text Generation','Chat','Code'], description:'Fast, affordable conversational AI ideal for high-volume apps where cost efficiency matters more than frontier performance.', contextWindow:16385, pricing:{input:0.5,output:1.5,unit:'per 1M tokens',tier:'budget'}, strengths:['Very low cost','Fast inference','Good for structured tasks','Stable API'], limitations:['Weaker reasoning vs GPT-4','No vision','Smaller context'], scores:{reasoning:68,coding:70,creativity:65,speed:95,multimodal:0,contextHandling:55,costEfficiency:95}, releaseDate:'2023-03', openSource:false, apiAvailable:true },
  { slug:'gpt-4o-mini', name:'GPT-4o Mini', provider:'OpenAI', providerColor:'#10a37f', categories:['Text Generation','Chat','Code','Speed'], description:"OpenAI's affordable multimodal model outperforming GPT-3.5 on most benchmarks at a fraction of the cost.", contextWindow:128000, pricing:{input:0.15,output:0.6,unit:'per 1M tokens',tier:'budget'}, strengths:['Very affordable','Multimodal capable','Fast responses','Outperforms GPT-3.5','128K context'], limitations:['Less capable than GPT-4o','Not for complex reasoning','Lower ceiling'], scores:{reasoning:78,coding:80,creativity:74,speed:92,multimodal:82,contextHandling:88,costEfficiency:93}, releaseDate:'2024-07', openSource:false, apiAvailable:true },
  { slug:'claude-3-5-sonnet', name:'Claude 3.5 Sonnet', provider:'Anthropic', providerColor:'#d4794a', categories:['Text Generation','Reasoning','Code','Chat','Analysis'], description:"Anthropic's most intelligent model with frontier reasoning, best-in-class coding, and 200K context window.", contextWindow:200000, pricing:{input:3.0,output:15.0,unit:'per 1M tokens',tier:'mid'}, strengths:['Top-tier coding benchmarks','200K context','Constitutional AI safety','Strong nuanced analysis','Excellent instruction following'], limitations:['No image generation','Higher output cost','Slower than Haiku'], scores:{reasoning:97,coding:98,creativity:90,speed:78,multimodal:75,contextHandling:98,costEfficiency:68}, releaseDate:'2024-10', openSource:false, apiAvailable:true },
  { slug:'claude-3-opus', name:'Claude 3 Opus', provider:'Anthropic', providerColor:'#d4794a', categories:['Text Generation','Reasoning','Research','Analysis'], description:"Anthropic's most powerful model for highly complex reasoning, nuanced content, and deep comprehension.", contextWindow:200000, pricing:{input:15.0,output:75.0,unit:'per 1M tokens',tier:'premium'}, strengths:['Graduate-level reasoning','Best for complex research','Nuanced long-form writing','Exceptional comprehension'], limitations:['Most expensive Claude model','Slower response times','Overkill for simple tasks'], scores:{reasoning:99,coding:88,creativity:95,speed:55,multimodal:72,contextHandling:98,costEfficiency:30}, releaseDate:'2024-03', openSource:false, apiAvailable:true },
  { slug:'claude-3-haiku', name:'Claude 3 Haiku', provider:'Anthropic', providerColor:'#d4794a', categories:['Text Generation','Chat','Code','Speed'], description:"Anthropic's fastest compact model for near-instant responsiveness and cost-sensitive production applications.", contextWindow:200000, pricing:{input:0.25,output:1.25,unit:'per 1M tokens',tier:'budget'}, strengths:['Extremely fast','Very affordable','Good for production at scale','Reliable outputs'], limitations:['Less capable for complex reasoning','Weaker advanced coding'], scores:{reasoning:72,coding:74,creativity:68,speed:98,multimodal:70,contextHandling:90,costEfficiency:97}, releaseDate:'2024-03', openSource:false, apiAvailable:true },
  { slug:'gemini-1-5-pro', name:'Gemini 1.5 Pro', provider:'Google', providerColor:'#4285f4', categories:['Text Generation','Multimodal','Code','Reasoning','Research'], description:"Google's most capable model with 1M token context, native video understanding, and cross-modal reasoning.", contextWindow:1000000, pricing:{input:3.5,output:10.5,unit:'per 1M tokens',tier:'mid'}, strengths:['1M token context','Native video understanding','Cross-modal reasoning','Excellent long document analysis'], limitations:['Can be slower on very long contexts','Pricing scales with context','Variable consistency'], scores:{reasoning:92,coding:85,creativity:84,speed:75,multimodal:95,contextHandling:100,costEfficiency:70}, releaseDate:'2024-05', openSource:false, apiAvailable:true },
  { slug:'gemini-1-5-flash', name:'Gemini 1.5 Flash', provider:'Google', providerColor:'#4285f4', categories:['Text Generation','Multimodal','Chat','Speed'], description:"Google's fast, cost-efficient multimodal model with 1M context at a fraction of Pro's cost.", contextWindow:1000000, pricing:{input:0.075,output:0.3,unit:'per 1M tokens',tier:'budget'}, strengths:['Extremely cost-efficient','1M context at low cost','Multimodal support','Fast responses'], limitations:['Less accurate than Pro','Weaker complex reasoning'], scores:{reasoning:78,coding:75,creativity:72,speed:93,multimodal:85,contextHandling:100,costEfficiency:98}, releaseDate:'2024-05', openSource:false, apiAvailable:true },
  { slug:'gemini-ultra', name:'Gemini Ultra', provider:'Google', providerColor:'#4285f4', categories:['Text Generation','Multimodal','Reasoning','Research'], description:"Google's most powerful model achieving SOTA on MMLU benchmarks for expert-level multimodal tasks.", contextWindow:32000, pricing:{input:20.0,output:60.0,unit:'per 1M tokens',tier:'premium'}, strengths:['MMLU benchmark leader','Complex multimodal reasoning','Scientific problem solving'], limitations:['Very expensive','Smaller context than Pro','Limited availability'], scores:{reasoning:96,coding:87,creativity:86,speed:60,multimodal:96,contextHandling:70,costEfficiency:25}, releaseDate:'2024-02', openSource:false, apiAvailable:true },
  { slug:'llama-3-1-405b', name:'Llama 3.1 405B', provider:'Meta', providerColor:'#0668e1', categories:['Text Generation','Reasoning','Code','Research'], description:"Meta's largest open-source model matching GPT-4 benchmarks with fully open weights for on-premise deployment.", contextWindow:128000, pricing:{input:3.0,output:3.0,unit:'per 1M tokens (hosted)',tier:'mid'}, strengths:['Open source / self-hostable','No data privacy concerns','Competitive with GPT-4','Fine-tunable'], limitations:['High compute for self-hosting','Slower than proprietary models'], scores:{reasoning:89,coding:86,creativity:82,speed:60,multimodal:40,contextHandling:88,costEfficiency:80}, releaseDate:'2024-07', openSource:true, apiAvailable:true },
  { slug:'llama-3-1-70b', name:'Llama 3.1 70B', provider:'Meta', providerColor:'#0668e1', categories:['Text Generation','Code','Chat','Reasoning'], description:"Meta's mid-size open model balancing capability, efficiency, and strong multilingual support.", contextWindow:128000, pricing:{input:0.59,output:0.79,unit:'per 1M tokens (hosted)',tier:'budget'}, strengths:['Open source','Cost-effective at scale','Strong multilingual','Good reasoning for size'], limitations:['Weaker than 405B on complex tasks','No native vision'], scores:{reasoning:80,coding:78,creativity:75,speed:78,multimodal:0,contextHandling:85,costEfficiency:90}, releaseDate:'2024-07', openSource:true, apiAvailable:true },
  { slug:'mistral-large', name:'Mistral Large', provider:'Mistral AI', providerColor:'#ff6b35', categories:['Text Generation','Reasoning','Code','Multilingual'], description:"Mistral AI's flagship model with native function calling and excellent French/German/Spanish support.", contextWindow:128000, pricing:{input:3.0,output:9.0,unit:'per 1M tokens',tier:'mid'}, strengths:['Strong multilingual support','Native function calling','Good reasoning','European data compliance'], limitations:['Smaller ecosystem','No native image understanding'], scores:{reasoning:85,coding:82,creativity:78,speed:80,multimodal:0,contextHandling:85,costEfficiency:75}, releaseDate:'2024-02', openSource:false, apiAvailable:true },
  { slug:'dalle-3', name:'DALL·E 3', provider:'OpenAI', providerColor:'#10a37f', categories:['Image Generation','Creative','Multimodal'], description:"OpenAI's SOTA image generation model with exceptional prompt adherence and photorealistic outputs.", contextWindow:null, pricing:{input:0.04,unit:'per image (1024×1024)',tier:'mid'}, strengths:['Exceptional prompt adherence','Photorealistic outputs','ChatGPT integration','Text in images'], limitations:['Per-image pricing','Content restrictions','Less artistic control than Midjourney'], scores:{reasoning:0,coding:0,creativity:93,speed:72,multimodal:95,contextHandling:0,costEfficiency:65}, releaseDate:'2023-10', openSource:false, apiAvailable:true },
  { slug:'stable-diffusion-xl', name:'Stable Diffusion XL', provider:'Stability AI', providerColor:'#7c3aed', categories:['Image Generation','Creative','Open Source'], description:"Stability AI's open-source image model for local deployment with full customization and no per-image costs.", contextWindow:null, pricing:{input:0.0,unit:'free (self-hosted)',tier:'free'}, strengths:['Fully open source','Local deployment','Highly customizable','No per-image costs'], limitations:['Requires GPU','More complex setup','Weaker prompt adherence vs DALL·E 3'], scores:{reasoning:0,coding:0,creativity:88,speed:65,multimodal:90,contextHandling:0,costEfficiency:100}, releaseDate:'2023-07', openSource:true, apiAvailable:true },
  { slug:'midjourney-v6', name:'Midjourney V6', provider:'Midjourney', providerColor:'#e63946', categories:['Image Generation','Creative','Art'], description:"Midjourney's flagship artistic model with unmatched aesthetics for cinematic and concept art generation.", contextWindow:null, pricing:{input:10.0,unit:'per month (basic plan)',tier:'mid'}, strengths:['Unmatched artistic quality','Cinematic outputs','Unique visual style','Style mixing'], limitations:['Discord-based interface','No API access','Subscription-only'], scores:{reasoning:0,coding:0,creativity:98,speed:68,multimodal:88,contextHandling:0,costEfficiency:60}, releaseDate:'2024-01', openSource:false, apiAvailable:false },
  { slug:'whisper', name:'Whisper', provider:'OpenAI', providerColor:'#10a37f', categories:['Audio','Speech-to-Text','Transcription','Translation'], description:"OpenAI's speech recognition model trained on 680K hours of audio, supporting 99 languages with near-human accuracy.", contextWindow:null, pricing:{input:0.006,unit:'per minute of audio',tier:'budget'}, strengths:['99-language support','Near-human accuracy','Open source weights','Translation to English','Noise robustness'], limitations:['No speaker diarization','Latency on large model','Struggles with heavy accents'], scores:{reasoning:0,coding:0,creativity:30,speed:78,multimodal:80,contextHandling:0,costEfficiency:95}, releaseDate:'2022-09', openSource:true, apiAvailable:true },
  { slug:'gemma-2', name:'Gemma 2', provider:'Google', providerColor:'#4285f4', categories:['Text Generation','Code','Chat','Open Source'], description:"Google's lightweight open-source model outperforming models twice its size, designed for responsible AI on consumer hardware.", contextWindow:8192, pricing:{input:0.0,unit:'free (open weights)',tier:'free'}, strengths:['Open weights','Runs on consumer hardware','Responsible AI focus','Local deployment'], limitations:['Smaller context window','Not for complex reasoning','Limited multimodal'], scores:{reasoning:74,coding:73,creativity:70,speed:90,multimodal:20,contextHandling:45,costEfficiency:100}, releaseDate:'2024-06', openSource:true, apiAvailable:true },
  { slug:'phi-3-mini', name:'Phi-3 Mini', provider:'Microsoft', providerColor:'#00a4ef', categories:['Text Generation','Code','Open Source','Speed'], description:"Microsoft's 3.8B parameter open-source model outperforming models 10× its size on coding benchmarks. Ideal for edge/mobile.", contextWindow:128000, pricing:{input:0.0,unit:'free (open weights)',tier:'free'}, strengths:['Edge/mobile deployment','Tiny footprint','Strong coding for size','128K context'], limitations:['Less capable than large models','Weaker complex reasoning','Limited creativity'], scores:{reasoning:70,coding:76,creativity:60,speed:99,multimodal:0,contextHandling:85,costEfficiency:100}, releaseDate:'2024-04', openSource:true, apiAvailable:true },
  { slug:'command-r-plus', name:'Command R+', provider:'Cohere', providerColor:'#39d353', categories:['Text Generation','Reasoning','RAG','Enterprise'], description:"Cohere's enterprise model optimized for RAG, grounded responses, and complex business document workflows.", contextWindow:128000, pricing:{input:3.0,output:15.0,unit:'per 1M tokens',tier:'mid'}, strengths:['RAG-optimized architecture','100+ language support','Enterprise security','Citation grounding'], limitations:['Less known ecosystem','Weaker creative writing','No image understanding'], scores:{reasoning:83,coding:78,creativity:70,speed:80,multimodal:0,contextHandling:88,costEfficiency:72}, releaseDate:'2024-04', openSource:false, apiAvailable:true },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');
    await AIModel.deleteMany({});
    console.log('Cleared existing models');
    await AIModel.insertMany(models);
    console.log(`Seeded ${models.length} AI models`);
    await mongoose.disconnect();
    console.log('Done.');
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();
